import { Banco } from "./validar-iban.model";

export const codigoDeBancos: Banco[] = [
  { codigoBanco: "2080", nombreDeBanco: "Abanca Corporación Bancaria" },
  { codigoBanco: "0061", nombreDeBanco: "Banca March" },
  { codigoBanco: "0188", nombreDeBanco: "Banco Alcalá" },
  { codigoBanco: "0182", nombreDeBanco: "Banco Bilbao Vizcaya Argentaria" },
  { codigoBanco: "0130", nombreDeBanco: "Banco Caixa Geral" },
  { codigoBanco: "0234", nombreDeBanco: "Banco Caminos" },
  { codigoBanco: "2105", nombreDeBanco: "Banco Castilla-La Mancha" },
  { codigoBanco: "0240", nombreDeBanco: "Banco de Crédito Social Cooperativo" },
  { codigoBanco: "0081", nombreDeBanco: "Banco de Sabadell" },
  { codigoBanco: "0487", nombreDeBanco: "Banco Mare Nostrum" },
  { codigoBanco: "0186", nombreDeBanco: "Banco Mediolanum" },
  { codigoBanco: "0238", nombreDeBanco: "Banco Pastor" },
  { codigoBanco: "0075", nombreDeBanco: "Banco Popular Español" },
  { codigoBanco: "0049", nombreDeBanco: "Banco Santander" },
  { codigoBanco: "3873", nombreDeBanco: "Banco Santander Totta" },
  { codigoBanco: "2038", nombreDeBanco: "Bankia" },
  { codigoBanco: "0128", nombreDeBanco: "Bankinter" },
  { codigoBanco: "0138", nombreDeBanco: "Bankoa" },
  { codigoBanco: "0152", nombreDeBanco: "Barclays Bank PLC" },
  { codigoBanco: "3842", nombreDeBanco: "BNP Paribas Paris" },
  { codigoBanco: "3025", nombreDeBanco: "Caixa de Credit del Enginyers" },
  { codigoBanco: "2100", nombreDeBanco: "Caixabank" },
  {
    codigoBanco: "2045",
    nombreDeBanco: "Caja de Ahorros y Monte de Piedad de Ontinyent",
  },
  { codigoBanco: "3035", nombreDeBanco: "Caja Laboral Popular CC" },
  { codigoBanco: "3081", nombreDeBanco: "Caja Rural Castilla-La Mancha" },
  { codigoBanco: "3058", nombreDeBanco: "Cajamar Caja Rural" },
  { codigoBanco: "2000", nombreDeBanco: "Cecabank" },
  { codigoBanco: "1474", nombreDeBanco: "Citibank Europe PLC" },
  { codigoBanco: "3821", nombreDeBanco: "Commerzbank AG" },
  { codigoBanco: "3877", nombreDeBanco: "Danske Bank A/S" },
  { codigoBanco: "0019", nombreDeBanco: "Deutsche Bank SAE" },
  { codigoBanco: "0239", nombreDeBanco: "EVO Banco" },
  { codigoBanco: "2085", nombreDeBanco: "Ibercaja Banco" },
  { codigoBanco: "1465", nombreDeBanco: "ING Bank NV" },
  { codigoBanco: "2095", nombreDeBanco: "Kutxabank" },
  { codigoBanco: "2048", nombreDeBanco: "Liberbank" },
  { codigoBanco: "0131", nombreDeBanco: "Novo Banco" },
  { codigoBanco: "0073", nombreDeBanco: "Open Bank" },
  { codigoBanco: "0108", nombreDeBanco: "Société Générale" },
  { codigoBanco: "2103", nombreDeBanco: "Unicaja Banco" },
];
